# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x,]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    
   deploy:
     needs: build
     runs-on: ubuntu-latest

     steps:
     - name: deploy to comtainer
       if: always()
       uses: fifsky/ssh-action@master
       with:
         host: 52.165.20.201
         user: administration
         pass: Pass123456789
         port: 22
     - run: echo `pwd`  
     - run: echo `whoami`
     - run: git init
     - run: git remote add origin git@github.com:jyotisable/github-action-CI-CD.git
     - run: git pull origin main
     - run: echo `pwd`
     - run: cd github-action-CI-CD
     - run: echo `pwd`
     - run: npm install --production
     - run: node server.js

         
